[program:uztransport]
command=/home/ubuntu/uztransport/venv/bin/daphne -b 127.0.0.1 -p 8000 core.asgi:application
directory=/home/ubuntu/uztransport
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/uztransport/app.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
environment=DJANGO_SETTINGS_MODULE="core.settings"

[program:uztransport-celery]
command=/home/ubuntu/uztransport/venv/bin/celery -A core worker --loglevel=info
directory=/home/ubuntu/uztransport
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/uztransport/celery.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3

[group:uztransport-all]
programs=uztransport,uztransport-celery
